const data = [
    {
        id: 1,
        image: require('../images/portfolio/portfolio1.jpg'),
        url: "https://www.thedal.co.in/",
        title: "Thedal Website",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'thedal',
   },
    {
        id: 2,
        image: require('../images/portfolio/portfolio2.jpg'),
        url: "http://kitecareer.com/bjmm",
        title: "BJMM Mobile App",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "mobile app",
        type: 'bjmm',
    },
    {
        id: 3,
        image: require('../images/portfolio/portfolio3.jpg'),
        url: "http://kitecareer.com/dsrconstruction/",
        title: "DSR Construction",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'dsr',
    },
    {
        id: 4,
        image: require('../images/portfolio/portfolio4.jpg'),
        url: "http://kitecareer.com/akhilconsultancy/",
        title: "Akhil Consultancy",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'akil',
    },
    {
        id: 5,
        image: require('../images/portfolio/portfolio5.jpg'),
        url: "http://kitecareer.com/wonderart/",
        title: "WonderArt",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'wonderart',
    },
    {
        id: 6,
        image: require('../images/portfolio/portfolio6.jpg'),
        url: "http://kitecareer.com/bestvijay/",
        title: "Best Vijay",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'bestvijay',
    },
    {
        id: 7,
        image: require('../images/portfolio/portfolio7.jpg'),
        url: "http://kitecareer.com/eeratechnology/",
        title: "EERA Technology",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'eera',
    },
    {
        id: 8,
        image: require('../images/portfolio/portfolio8.jpg'),
        url: "http://transcloudservices.com/",
        title: "TransCloudServices",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "website",
        type: 'transcloud',
    },
    {
        id: 9,
        image: require('../images/portfolio/portfolio9.jpg'),
        title: "Women's Day",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
        category: "brochure",
        type: 'transcloud',
    },
    {
        id: 10,
        image: require('../images/portfolio/portfolio10.jpg'),
        title: "Thedal",
        category: "client",
        type: 'transcloud',
    },
    {
        id: 11,
        image: require('../images/portfolio/portfolio11.jpg'),
        title: "BJMM",
        category: "client",
        type: 'transcloud',
    },
    {
        id: 12,
        image: require('../images/portfolio/portfolio12.jpg'),
        title: "DSR Construction",
        category: "client",
        type: 'transcloud',
    },
    {
        id: 13,
        image: require('../images/portfolio/portfolio13.jpg'),
        title: "TNSC",
        category: "client",
        type: 'transcloud',
    },
    {
        id: 14,
        image: require('../images/portfolio/portfolio14.jpg'),
        title: "Nithish",
        category: "client",
        type: 'transcloud',
    },
    {
        id: 15,
        image: require('../images/portfolio/portfolio15.jpg'),
        title: "nu Technology",
        category: "client",
        type: 'transcloud',
    },                    
  ]
export default data;